version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: toeic_user
      MYSQL_ROOT_PASSWORD:
    ports:
      - "3307:3306"
  authservice:
    image: ${DOCKER_REGISTRY-}authservice
    build:
      context: .
      dockerfile: AuthService/Dockerfile
    depends_on:
      - db
    ports:
      - "5555:80"

volumes:
  mysql_data:
