version: '3.8'

services:  
  authservice:
    image: ${DOCKER_REGISTRY-}authservice
    build:
      context: .
      dockerfile: AuthService/Dockerfile
    ports:
      - "5556:81"  # Map host port 5556 to container port 81
    environment:
      ASPNETCORE_URLS: "https://*:81"  # Đảm bảo trùng với port mapping
      ConnectionStrings__DefaultConnection: "Server=sql300.infinityfree.com;Database=if0_37693544_toeic_user;User=if0_37693544;Password=v0xmJqQ3UH"
