version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: toeic_user
      MYSQL_ROOT_PASSWORD: ""
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  authservice:
    image: ${DOCKER_REGISTRY-}authservice
    build:
      context: .
      dockerfile: AuthService/Dockerfile
    depends_on:
      - db
    ports:
      - "5556:81"  # Map host port 5555 to container port 80
    environment:
      ASPNETCORE_URLS: "https://*:81"  # Ensure this matches the port mapping
      ConnectionStrings__DefaultConnection: "Server=db;Database=toeic_user;User=root;Password="

volumes:
  mysql_data:
