version: '3.8'

services:  
  authservice:
    image: ${DOCKER_REGISTRY-}authservice
    build:
      context: .
      dockerfile: AuthService/Dockerfile
    ports:
      - "5556:81"  # Map host port 5556 to container port 81
    environment:
      ASPNETCORE_URLS: "https://*:81"  # Đảm bảo trùng với port mapping
      ConnectionStrings__DefaultConnection: "sql12.freemysqlhosting.net;Database=sql12744110;User=sql12744110;Password=DhbU7Sf4wZ"
